#!/usr/bin/env bash
# Change localhost and facebook.com IP addresses

# Update localhost to 127.0.0.2
sed -i 's/127.0.0.1[[:space:]]*localhost/127.0.0.2 localhost/' /etc/hosts

# Update facebook.com to 8.8.8.8
sed -i '/facebook.com/d' /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts	
